---
title: "My own web-page"
author: "Vera Kuklina"
date: "8/16/2018"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

#clever thing that will be explored later
```{r}
suppressPackageStartupMessages({
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
})
```

# Load salmon data from KNB site
```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1"
# data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"
esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

```{r}
median_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
#to separate Year, Month and Day
    group_by(Species, SASAP.Region, Year, Location) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
    group_by(Species) %>% 
  summarize(median_escapement = median(escapement))

head(median_esc)
```
#Plot the escapement as a bar chart
```{r}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```
#Work on building interactive map

We are starting from daily escapement data again, and finding the unique locations at which escapement was measured

## Find unique location plot

Make sure to deal with missing values in the location field.


```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
datatable(locations)
```

## Draw the map

```{r}
leaflet(locations) %>% 
   addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)
#it's also possible to add vectors (lines, poligons, points) from shapefiles)
```

```{r}
locs <- locations %>% mutate(Longitude = abs(Longitude) * -1)

leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)
```

```{r}
change
```

